spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # 正式環境避免亂改資料表
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/ProSync?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baselineOnMigrate: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 2